services:
  # 1. MongoDB (Primary Database)
  mongodb:
    image: mongo:latest
    container_name: welookup-mongodb
    ports:
      - "27017:27017" # Map container port to host machine
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INIT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INIT_PASSWORD}
    volumes:
      - mongodb_data:/data/db # Persistent storage for data

  # 2. RabbitMQ (Message Broker)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: welookup-rabbitmq
    ports:
      - "5672:5672" # AMQP protocol (for communication)
      - "15672:15672" # Management UI (for checking queues)
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  verification-service:
    # Build using the Dockerfile inside the verification-service directory
    build: 
      context: ./backend-services/verification-service
      dockerfile: Dockerfile
    container_name: welookup-verification-service
    # Restart policy is crucial for workers to maintain reliability
    restart: always 
    environment:
      - NODE_ENV=production
      # It relies on the environment variables defined in its local .env file
    # Ensure it starts only after its dependencies are up
    depends_on:
      - mongodb
      - rabbitmq

  # 4. API Gateway (Main Entry Point)
  api-gateway:
    build:
      context: ./backend-services/api-gateway
      dockerfile: Dockerfile
    container_name: welookup-api-gateway
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://welookup_admin:mongo123service@mongodb:27017/welookupDB?authSource=admin
      - RABBITMQ_URI=amqp://welookup_guest:rabbitmq456service@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq

  # 5. Scorer Service
  scoring-service:
    build: 
      context: ./backend-services/scoring-service
      dockerfile: Dockerfile
    container_name: welookup-scoring-service
    restart: always
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  mongodb_data: # Define the persistent volume